@startuml
'https://plantuml.com/class-diagram

class ChannelData extends MeasureData

class AreaChannelData extends ChannelData

class SampleCameraData extends AreaChannelData {
    beam_x : int
    beam_y : int
}

class ScientificCameraData extends AreaChannelData {
    roi[] : ScientificCameraROIData
    acquire_time : float | np.ndarray
    {field} temperature : np.ndarray(dtype=float)
    {field} humidity : np.ndarray(dtype=float)
}

together {
    class ScientificCameraData
    class ScientificCameraROIData
}

ScientificCameraROIData -[hidden]> ScientificCameraData
ScientificCameraROIData "0..n" -* ScientificCameraData
ScientificCameraROIData -[hidden]> ScientificCameraData

class ScientificCameraROIData extends MeasureData {
    {field} label : string
    {field} marker : np.ndarray(dtype=int)
    background_width : int
    {field} min_value : np.ndarray(dtype=float)
    {field} min_x : np.ndarray(dtype=float)
    {field} min_y : np.ndarray(dtype=float)
    {field} max_value : np.ndarray(dtype=float)
    {field} max_x : np.ndarray(dtype=float)
    {field} max_y : np.ndarray(dtype=float)
    {field} mean : np.ndarray(dtype=float)
    {field} total : np.ndarray(dtype=float)
    {field} net : np.ndarray(dtype=float)
    {field} sigma : np.ndarray(dtype=float)
    centroid_threshold : float
    {field} centroid_x : np.ndarray(dtype=float)
    {field} centroid_y : np.ndarray(dtype=float)
    {field} centroid_sigma_x : np.ndarray(dtype=float)
    {field} centroid_sigma_y : np.ndarray(dtype=float)
    {field} centroid_sigma_xy : np.ndarray(dtype=float)
}

@enduml