@startuml
'https://plantuml.com/class-diagram

class ArrayChannelData extends ChannelData {}

together {
class ScopeChannelData extends ArrayChannelData

class MCAChannelData extends ArrayChannelData {
    roi[] : MCAChannelROIData
    life_time : np.ndarray
    real_time : np.ndarray
    preset_life_time : np.ndarray
    preset_real_time : np.ndarray
}

MCAChannelROIData "0..n" -* MCAChannelData

class MCAChannelROIData extends ChannelData {
    {field} label : string
    {field} marker : np.ndarray(dtype=int)
}

class ScopeData {
    channels[] : ScopeChannelData
}

ScopeChannelData "0..n" -* ScopeData

}

@enduml