@startuml

class Metadata {
    name : string
}

class Data {
}
note bottom: See diagram for\ndata module.

interface DeviceMetadata {
    id : string
    pv : string
    access_mode : string
}

class MeasureMetadata extends Metadata {
    unit : string
}

class MonitorMetadata extends Metadata implements DeviceMetadata {
}

class AxisMetadata extends MeasureMetadata implements DeviceMetadata  {
}

class ChannelMetadata extends MeasureMetadata implements DeviceMetadata  {
}

class TimestampMetadata extends MeasureMetadata {
}

class SinglePointChannelMetadata extends ChannelMetadata {}

class AverageChannelMetadata extends ChannelMetadata {
    n_averages : integer
    low_limit : float
    max_attempts : integer
    max_deviation : float
}

class IntervalChannelMetadata extends ChannelMetadata {
    trigger_interval : float
}

class ArrayChannelMetadata extends ChannelMetadata {
}

class AreaChannelMetadata extends ChannelMetadata {
}

Data *- Metadata

interface NormalizedMetadata {
    normalize_id : string
}

class SinglePointNormalizedChannelMetadata extends SinglePointChannelMetadata implements NormalizedMetadata {}

class AverageNormalizedChannelMetadata extends AverageChannelMetadata implements NormalizedMetadata {}

class IntervalNormalizedChannelMetadata extends IntervalChannelMetadata implements NormalizedMetadata {}

@enduml
