@startuml
'https://plantuml.com/class-diagram

class Measurement extends measurement.entities.measurement.Measurement {
    detectors{} : ChannelData
    motors{} : AxisData
    machine{} : DeviceData
    beamline{} : DeviceData
    metadata : Metadata
    scan : Scan
    setup : Setup
    log_messages[] : LogMessage
    data : Data

    load(filename)
    save(filename)
    export(filename, format)
    set_data(name, field)
    set_axes(name[])
}

Measurement *-- measurement.entities.metadata.Metadata
Measurement *-- Scan
Measurement *-- Setup

class evefile.entities.file.Scan {
}

class evefile.entities.file.Setup {
}

class Scan extends evefile.entities.file.Scan

class Setup extends evefile.entities.file.Setup

class measurement.entities.measurement.Data {
    data : np.ndarray
    axes[]: AxisData
    metadata : DeviceMetadata
}

class measurement.entities.measurement.Axis {
    data : np.ndarray
    label: string
    measure : string
    symbol : string
    unit : string
}

Data *-"n" Axis

Data -* Measurement

measurement.entities.metadata.Metadata -[hidden]-> Measurement

measurement.entities.measurement.Data -[hidden]> Measurement

@enduml