@startuml
'skinparam dpi 150

package evedata {

    package evedata.evefile {
    }

    package evedata.measurement {
    }

    evedata.evefile <-- evedata.measurement

}

package eveH5 #fff9c4
eveH5 -0)-- evedata.evefile

package SCML #fff9c4
SCML -0)-- evedata.evefile

package evedataviewer #fff9c4
evedata.measurement --(0- evedataviewer

package radiometry #fff9c4
evedata.measurement --(0- radiometry

@enduml
