@startuml
'skinparam dpi 150

package evedata {
    package evedata.scan {
        package evedata.scan.boundaries {
            package scan {}
            package scml {}
            scan -> scml
        }
        package evedata.scan.controllers {
            package version_mapping {}
        }
        package evedata.scan.entities {
            package file {
            }
            package setup {
            }
            package scan {
            }
            package event {
            }
            package plot {
            }

            file -down-> setup
            file -down-> scan
            scan -down-> event
            scan -down-> plot
        }
        evedata.scan.boundaries --> evedata.scan.controllers
        evedata.scan.controllers --> evedata.scan.entities
    }

    package evedata.evefile {
        package evedata.evefile.boundaries {
            package evefile {}
            package eveh5 {}
            evefile -> eveh5
        }
        package evedata.evefile.controllers {
            package transforming {}
            package version_mapping {}
        }
        package evedata.evefile.entities {
            package evedata.evefile.entities.file {
            }
            package evedata.evefile.entities.data {
            }
            package evedata.evefile.entities.metadata {
            }
            file -down-> data
            data -down-> metadata

        }
        evedata.evefile.boundaries --> evedata.evefile.controllers
        evedata.evefile.controllers --> evedata.evefile.entities
    }

    package evedata.measurement {
        package evedata.measurement.boundaries {
            package measurement {}
        }
        package evedata.measurement.controllers {
            package transforming {}
            package joining {}
        }
        package evedata.measurement.entities {
            package measurement {}
            package metadata {}
            measurement -down-> metadata
        }

        evedata.measurement.boundaries --> evedata.measurement.controllers
        evedata.measurement.controllers --> evedata.measurement.entities
    }
}

@enduml
