@startuml
'skinparam dpi 150

package evedata {

    package evedata.evefile {
    }

    package evedata.dataset {
    }

}

evedata.evefile <-- evedata.dataset

package eveH5 #fff9c4
eveH5 <-- evedata.evefile

package evedataviewer #fff9c4
package radiometry #fff9c4

evedata.dataset <-- evedataviewer
evedata.dataset <-- radiometry
@enduml
