@startuml
'skinparam dpi 150

package evedata {
    package evedata.scan {
        package evedata.scan.boundaries {
            package scan {}
            package scml {}
        }
        package evedata.scan.controllers {
            package version_mapping {}
        }
        package evedata.scan.entities {
            package file {
            }
            package setup {
            }
            package scan {
            }
            package event {
            }
            package plot {
            }

            setup <-- file
            scan <-- file
            event <-- scan
            plot <-- scan
        }
        evedata.scan.boundaries --> evedata.scan.controllers
        evedata.scan.controllers --> evedata.scan.entities
    }

    package evedata.evefile {
        package evedata.evefile.boundaries {
            package evefile {}
            package eveH5 {}
        }
        package evedata.evefile.controllers {
            package version_mapping {}
            package transforming {}
        }
        package evedata.evefile.entities {
            package evedata.evefile.entities.file {
            }
            package evedata.evefile.entities.data {
            }
            package evedata.evefile.entities.metadata {
            }

            evedata.evefile.entities.metadata <-- evedata.evefile.entities.data
            evedata.evefile.entities.data <-- evedata.evefile.entities.file
        }
        evedata.evefile.boundaries --> evedata.evefile.controllers
        evedata.evefile.controllers --> evedata.evefile.entities
    }

    package evedata.measurement {
        package evedata.measurement.boundaries {
            package measurement {}
        }
        package evedata.measurement.controllers {
            package transforming {}
            package filling {}
        }
        package evedata.measurement.entities {
            package data {}
            package metadata {}
        }

        evedata.measurement.boundaries --> evedata.measurement.controllers
        evedata.measurement.controllers --> evedata.measurement.entities
    }
}

@enduml
