@startuml

class EveFile {
    metadata : EveFileMetadata
    comments : Comment[]
    scml : SCML
    data : EveData[]
    snapshots : EveData[]
}
note left of EveFile::snapshots
    Snapshot datasets can have
    identical names/IDs to datasets
    in the standard section.
    This makes a separate list
    probably unavoidable.

    How to deal with monitors?
end note

EveFile *- "n" EveData
note bottom: See diagram for\ndata module.

class EveFileMetadata{
    filename : string
    h5_version : string
    eve_version : string
    xml_version: string
    location : string
    start : datetime
    end : datetime
    preferred_axis : string
    preferred_channel : string
    preferred_normalisation_channel : string
}

class Comment {
    timestamp : datetime
    comment : string
}
note bottom: Comments are both, file comment\nand log messages. Discriminating\ncould be done in the EveFile class. 

class SCML {
}
note bottom: See diagram for\nscml subpackage.

EveFile *-- EveFileMetadata
EveFile "1" *-- "n" Comment
EveFile *-- SCML

@enduml
