@startuml

class Metadata {
    name : string
}

class Data {
}
note bottom: See diagram for\ndata module.

interface DeviceMetadata {
    id : string
    pv : string
    transport_type : string
}

class MeasureMetadata extends Metadata {
    unit : string
}

class MonitorMetadata extends Metadata implements DeviceMetadata {
}

class AxisMetadata extends MeasureMetadata implements DeviceMetadata  {
}

class ChannelMetadata extends MeasureMetadata implements DeviceMetadata  {
    normalise_id : string
}

class TimestampMetadata extends MeasureMetadata {
}

class StandardChannelMetadata extends ChannelMetadata {}

class AverageChannelMetadata extends ChannelMetadata {
    n_averages : integer
    low_limit : float
    max_attempts : integer
    max_deviation : float
}
note bottom
    These attributes may change for individual values
    if the channel is redefined in different scan modules
    and are currently saved in eveH5 for each position.

    As channels can be redefined from average to
    interval in different scan modules, they should
    be separated into individual datasets in any case
    and in the future saved as separate datasets in eveH5.
end note

class IntervalChannelMetadata extends ChannelMetadata {
    trigger_interval : float
}

class ArrayChannelMetadata extends ChannelMetadata {
}

class AreaChannelMetadata extends ChannelMetadata {
}

Data *- Metadata

@enduml
