@startuml

class EveFile {
    metadata : EveFileMetadata
    comments : Comment[]
    scml : SCML
    data : EveData[]
}
note left: Should data be split\ninto sections?

class EveFileMetadata{
    filename : String
    h5_version : String
    eve_version : String
    xml_version: String
    location : String
    start : DateTime
    end : DateTime
    preferred_axis : String
    preferred_channel : String
    preferred_normalisation_channel : String
}

class Comment {
    timestamp : DateTime
    comment : String
}
note bottom: Comments are both, file comment\nand log messages. Discriminating\ncould be done in the EveFile class. 

class SCML {
    metadata : SCMLMetadata
    xml: String
}
note top: xml is currently a string, but will\nbe replaced/amended by classes\nrepresenting the SCML contents

class SCMLMetadata {
    author: String
    version: String
}

EveFile *-- EveFileMetadata
EveFile "1" *-- "n" Comment
EveFile *-- SCML
SCML *-- SCMLMetadata

@enduml
