@startuml

class EveFile {
    metadata : EveFileMetadata
    comments : Comment[]
    scml : SCML
    data : EveData[]
}

class EveFileMetadata{
    filename : string
    h5_version : string
    eve_version : string
    xml_version: string
    location : string
    start : datetime
    end : datetime
    preferred_axis : string
    preferred_channel : string
    preferred_normalisation_channel : string
}

class Comment {
    timestamp : datetime
    comment : string
}
note bottom: Comments are both, file comment\nand log messages. Discriminating\ncould be done in the EveFile class. 

class SCML {
    metadata : SCMLMetadata
    xml: string
}
note top: xml is currently a string, but will\nbe replaced/amended by classes\nrepresenting the SCML contents

class SCMLMetadata {
    author: string
    version: string
}

EveFile *-- EveFileMetadata
EveFile "1" *-- "n" Comment
EveFile *-- SCML
SCML *-- SCMLMetadata

@enduml
