@startuml
'https://plantuml.com/class-diagram

interface File {
    version
    load()
}

class Scan extends scan.entities.file.File implements File {
    extract()
}

class Station extends scan.entities.file.File implements File {
}

@enduml