@startuml
'skinparam dpi 150

class Data {
    metadata : Metadata
    data : np.ndarray
}
note left of Data::data
    "data" usually contains a 1D array.

    For individual detector values see derived classes
    AverageDetectorData and IntervalDetectorData.

    ArrayDetectorData and ExternalData are somewhat
    special as they contain either 2D data or a list of
    data objects (in case of images and alike).
end note

class Metadata {
}
note bottom: See diagram for\nmetadata module.

class MeasureData {
    {field} positions : np.ndarray(dtype=int)
}

class MonitorData {
    {field} milliseconds : np.ndarray(dtype=int)
}

class MotorData {
}

class DetectorData {
}

class ExternalData {
    data : object[]
}

class TimestampData {
}

class AverageDetectorData {
    raw_values : raggedarray
    {field} attempts : np.ndarray(dtype=int)
    {field} n_averages : np.ndarray(dtype=int)
    mean()
    std()
    averaged_values()
    has_raw_values()
}
note bottom: How does mean() differ\nfrom values in Data?
note bottom of AverageDetectorData: averaged_values() returns only\nthose values used to average over

class IntervalDetectorData {
    raw_values : raggedarray
    {field} counts : np.ndarray(dtype=int)
    mean()
    std()
    has_raw_values()
}

class ArrayDetectorData {
}

Data *-- Metadata
Data <|-- MeasureData
Data <|-- MonitorData
MeasureData <|-- MotorData
MeasureData <|-- DetectorData
MeasureData <|-- ExternalData
MeasureData <|-- TimestampData
DetectorData <|-- AverageDetectorData
DetectorData <|-- IntervalDetectorData
DetectorData <|-- ArrayDetectorData

@enduml
