@startuml

class EveMetadata {
    name : string
    section : Section
}

class EveData {
}
note bottom: See separate diagram\nfor class hierarchy

enum Section {
    STANDARD
    SNAPSHOT
    MONITOR
    META
}

enum Transport {
    CA
    LOCAL
}
note bottom: This is defined in the\nscml.setup module\nas well. Generalise?

interface DeviceMetadata {
    id : string
    pv : string
    transport_type : Transport
}

class EveMeasureMetadata {
    unit : string
}

class EveMonitorMetadata implements DeviceMetadata {
    section : Section.MONITOR
}

class EveMotorMetadata implements DeviceMetadata  {
}

class EveDetectorMetadata implements DeviceMetadata  {
    normalise_id : string
}

class EveTimestampMetadata {
    section : Section.META
}

class EveScanModuleMetadata {
    section : Section.META
}

class EveAverageDetectorMetadata {
    n_averages : integer
    low_limit : float
    max_attempts : integer
    max_deviation : float
}
note bottom
    These attributes may change
     for individual values.

     Is that true even for only one
     detector in one scan module?
     If we go for separate detectors
     in this case, would it solve
     the problem?
end note

class EveIntervalDetectorMetadata {
    trigger_interval : float
}

EveData *- EveMetadata
EveMetadata <|-- EveMeasureMetadata
EveMetadata <|-- EveMonitorMetadata
EveMeasureMetadata <|-- EveDetectorMetadata
EveMeasureMetadata <|-- EveMotorMetadata
EveMeasureMetadata <|-- EveTimestampMetadata
EveMeasureMetadata <|-- EveScanModuleMetadata
EveDetectorMetadata <|-- EveAverageDetectorMetadata
EveDetectorMetadata <|-- EveIntervalDetectorMetadata

@enduml
