@startuml
'https://plantuml.com/class-diagram

class Plot {
    name : string
    xaxis : XAxis
    init : boolean
    yaxes : YAxis[]
    id : integer
}
Plot *-- XAxis
Plot *-- "1..2" YAxis
ScanModule *- "n" Plot

note bottom of ScanModule: See separate\nscan module

class PlotAxis {
    id : string
    mode : PlotMode
}
PlotAxis <|-- XAxis
PlotAxis <|-- YAxis
PlotAxis *-- PlotMode

class XAxis {
}

class YAxis {
    modifier : AxisModifier
    normalize_id : string
    linestyle : string
    color : string
    markstyle : string
}
YAxis *-- AxisModifier

enum AxisModifier {
    NONE
    INVERSE
}

enum PlotMode {
    linear
    log
}

@enduml