@startuml
'skinparam dpi 150

package evedata {

    package evedata.evefile {
    
        package evedata.evefile.file {
        }
        package evedata.evefile.data {
        }
        package evedata.evefile.metadata {
        }

        evedata.evefile.metadata <-- evedata.evefile.data
        evedata.evefile.data <-- evedata.evefile.file

    }

    package evedata.dataset {

        package evedata.dataset.dataset {
        }
        package evedata.dataset.metadata {
        }

        evedata.dataset.metadata <-- evedata.dataset.dataset
        
    }

    evedata.evefile <-- evedata.dataset

}

@enduml
