@startuml

class File {
    metadata : Metadata
    log_messages : LogMessage[]
    scan : Scan
    data : Data[]
    snapshots : Data[]
    monitors : Data[]
}

File *-- "n" Data
note bottom: See diagram for\ndata module.

class Metadata{
    filename : string
    h5_version : string
    eve_version : string
    xml_version: string
    measurement_station : string
    start : datetime
    end : datetime
    description : string
    simulation : boolean
    preferred_axis : string
    preferred_channel : string
    preferred_normalisation_channel : string
}

class LogMessage {
    timestamp : datetime
    comment : string
}

class Scan extends scan.boundaries.Scan {
    author : string
}
note left: See diagrams for\nscan subpackage.

File *-- Metadata
File "1" *-- "n" LogMessage
File *-- Scan

@enduml
