@startuml
'https://plantuml.com/class-diagram

class MeasureData {
    positions
    values
}

class Axis #pink extends MeasureData {}

class NonencodedAxis #pink extends Axis {}

class Channel extends MeasureData {}

class "Point (0D)" extends Channel {}

class SinglePoint extends "Point (0D)" {}

class Average extends "Point (0D)" {
    raw_values
    attempts
}

class Interval extends "Point (0D)" {
    raw_values
    counts
}

class "Array (1D)" extends Channel {}

class MCA extends "Array (1D)"

class Scope extends "Array (1D)"

class "Area (2D)" extends Channel {}

class ScientificCamera extends "Area (2D)"

class SampleCamera extends "Area (2D)"
@enduml